config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'users/index'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "static#home"
  namespace :owner do
    resources :restaurants
  end

  namespace :api do
    namespace :v1 do
      resources :restaurants
    end
  end

  # root "articles#index"
  resources :categories
  resources :restaurants, only: [:index, :show]
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :restaurants, dependent: :destroy

  validates :name, presence: true
end

app/models/menu.rb
class Menu < ApplicationRecord
end

app/models/menu_section.rb
class MenuSection < ApplicationRecord
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  belongs_to :owner, class_name: "User", foreign_key: "owner_id"
  belongs_to :category
  has_one_attached :profile do |attachable|
    attachable.variant :thumb, resize_to_limit: [200, 200]
  end

  has_one_attached :cover
  has_many_attached :images

  validates :profile,
            content_type: [:gif, :png, :jpg, :jpeg],
            size: { less_than: 2.megabytes , message: 'must be less than 2MB in size' }

  validates :cover,
            content_type: [:gif, :png, :jpg, :jpeg],
            size: { less_than: 5.megabytes , message: 'must be less than 5MB in size' }

  validates :name, presence: true, length: { maximum: 20, minimum: 2 }
  # validates :address, presence: true, format: { with: /\d/, message: "only allows number" }
end
# Category
# Cwner

app/models/section.rb
class Section < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :restaurants, class_name: "Restaurant", foreign_key: "owner_id"
  has_one_attached :avatar

  enum role: [:normal, :owner, :admin]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :load_category, only: [:show, :edit, :update, :destory]

  def index
    @categories = Category.all
  end

  def show
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_param)
    if @category.save
      redirect_to category_path(@category.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    if @category.update(category_param)
      redirect_to category_path(@category.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    load_category
    @category.destroy
    redirect_to categories_path
  end

  private
    def load_category
      @category = Category.find params[:id]
    end

    def category_param
      params.require(:category).permit(:name, :id)
    end
end

app/controllers/owner/restaurants_controller.rb
class Owner::RestaurantsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :only_owner, only: [:edit, :update, :destory]
  before_action :load_restaurant, only: [:show, :edit, :update, :destory]

  def index
    @restaurants = current_user.restaurants
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_param)
    if @restaurant.save
      redirect_to owner_restaurant_path(@restaurant.id)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    real_owner(@restaurant)
  end

  def update
    real_owner(@restaurant)
    if @restaurant.update(restaurant_param)
      redirect_to owner_restaurant_path(@restaurant.id)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    real_owner(@restaurant)
    @restaurant.destroy
    redirect_to restuaurants_path
  end

  private
    def load_restaurant
      @restaurant = Restaurant.find params[:id]
    end

    def only_owner
      unless current_user.owner?
        redirect_to root_path
        return
      end
    end

    def real_owner(restaurant)
      unless restaurant.owner_id == current_user.id
        redirect_to root_path
        return
      end
    end

    def restaurant_param
      params.require(:restaurant).permit(
        :name, :id, :category_id, :address, :profile,
        :cover, images: [])
    end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :load_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  private
    def load_restaurant
      @restaurant = Restaurant.find params[:id]
    end

    def restaurant_param
      params.require(:restaurant).permit(:name, :id, :category_id, :owner_id, :address)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/owner/restaurants_helper.rb
module Owner::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/_category.html.erb
<div>
  <h3><%= category.id %> <%= category.name %> </h3>
  <%= link_to("Back", categories_path) %>
  <%= link_to("Edit", edit_category_path(category.id)) %>
  <%= button_to 'delete', category_path(category.id), method: :delete,
    form: {data: {turbo_confirm: 'Are you sure?'}} %>
</div>

app/views/categories/_form.html.erb
<%= form_with model: @category do |form| %>
  <%= form.text_field :name %>
  <% if @category.errors.any? %>
    <ul>
      <%= @category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      <li>Hello</li>
    </ul>
  <% end %>
  <ul>
    <li>Hello</li>
  </ul>
  <%= form.submit %>
<% end %>

app/views/categories/index.html.erb
<ul>
  <% @categories.each do |category| %>
    <li>
      <%= render partial: "category", locals: {category: category } %>
      <%= link_to("Go to detail", category_path(category.id)) %>
    </li>
  <% end %>
</ul>

<%= link_to "New category", new_category_path %>

app/views/categories/show.html.erb
<%= render partial: "category", locals: {category: @category } %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyEmenuFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/owner/restaurants/_form.html.erb
<div class="row justify-content-center p-5">
  <div class="col-md-6">
    <%= form_with model: [:owner, @restaurant], class: "form-control" do |form| %>
      <div class="mb-3">
        <%= form.label :name, class: "form-label" %>
        <%= form.text_field :name, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :category_id, class: "form-label" %>
        <%= form.collection_select :category_id, Category.order(:name), :id, :name, {}, { class: "form-select"} %>
      </div>

      <div class="mb-3">
        <%= form.label :owner_id, class: "form-label" %>
        <%= form.collection_select :owner_id, User.order(:name), :id, :name, {}, { class: "form-select"} %>
      </div>

      <div class="mb-3">
        <%= form.label :profile, class: "form-label" %>
        <%= form.file_field :profile, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :cover, class: "form-label" %>
        <%= form.file_field :cover, class: "form-control" %>
      </div>

      <div class="mb-3">
        <%= form.label :images, class: "form-label" %>
        <%= form.file_field :images, class: "form-control", multiple: true %>
      </div>

      <div class="mb-3">
        <%= form.submit "Send", class: "btn btn-primary" %>
      </div>

      <% if @restaurant.errors.any? %>
        <ul>
        <% @restaurant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      <% end %>
    <% end %>
  </div>
</div>

app/views/owner/restaurants/edit.html.erb
<%= render "form" %>

app/views/owner/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to(restaurant.name, owner_restaurant_path(restaurant.id)) %>
    </li>
  <% end %>
</ul>

<%= link_to "New restaurant", new_owner_restaurant_path %>

app/views/owner/restaurants/new.html.erb
<%= render "form" %>

app/views/owner/restaurants/show.html.erb
<div class="row justify-content-center p-5">
  <div class="col-md-6">
    <ul class="list-group">
      <li class="list-group-item">
        ID:<b><%= @restaurant.id %></b>
      </li>
      <li class="list-group-item">
        Name:<b><%= @restaurant.name %></b>
      </li>
      <li class="list-group-item">
        Owner:<b><%= @restaurant.owner.email %></b>
      </li>
      <li class="list-group-item">
        Category: <b><%= @restaurant.category.name %></b>
      </li>
      <li class="list-group-item">
        Cover:
        <%= image_tag  @restaurant.cover.attached? ? @restaurant.cover : "male_avatar.png", class: "img-fluid" %>
      </li>

      <li class="list-group-item">
        Profile:
        <%= image_tag  @restaurant.profile.attached? ? @restaurant.profile.variant(:thumb) : "male_avatar.png", class: "img-fluid" %>
      </li>

      <li class="list-group-item">
        Image:
        <% if @restaurant.images.attached? %>
          <% @restaurant.images.each do |image| %>
            <%= image_tag image, class: "img-fluid" %>
          <% end %>
        <% end %>
      </li>

      <li class="list-group-item">
        <div class="row">
          <div class="col">
            <%= link_to("Back", owner_restaurants_path, class: "btn btn-secondary") %>
          </div>
          <div class="col">
            <%= link_to("Edit", edit_owner_restaurant_path(@restaurant.id), class: "btn btn-primary") %>
          </div>
          <div class="col">
            <%= button_to 'delete', owner_restaurant_path(@restaurant.id), class: "btn btn-danger", method: :delete,
              form: {data: {turbo_confirm: 'Are you sure?'}} %>
          </div>
        </div>
      </li>
    </ul>
  </div>
</div>

app/views/restaurants/index.html.erb
<ul>
  <% @restaurants.each do |restaurant| %>
    <li>
      <%= link_to(restaurant.name, restaurant_path(restaurant.id)) %>
    </li>
  <% end %>
</ul>

app/views/restaurants/show.html.erb
<div>
  <h3><%= @restaurant.id %> <%= @restaurant.name %> </h3>
  <h3>Owner: <%= @restaurant.owner.name %></h3>
  <h3>Category: <%= @restaurant.category.name %></h3>
  <%= link_to("Back", restaurants_path) %>
</div>

app/views/users/index.html.erb
<h1>Users#index</h1>
<p>Find me in app/views/users/index.html.erb</p>
<ul>

  <% @users.each do |user| %>
    <li>id: <%= user.id %>, name: <%= user.name %></li>
  <% end %>
</ul>